language: node_js
node_js:
  - "6"
os: 
  - osx
  - linux
addons:
  apt:
    packages:
      - libxss1
      - icnsutils 
      - graphicsmagick 
      - xz-utils
script:
  - webpack
after_success:
  - npm run dist